name: Test Coverage

on:
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Node.js 24.5.0
      uses: actions/setup-node@v4
      with:
        node-version: '24.5.0'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests with coverage on base branch
      run: |
        git checkout ${{ github.event.pull_request.base.sha }}
        npm ci
        npm run test:coverage
        cp coverage/coverage-summary.json coverage-base.json || echo "No base coverage found"
        
    - name: Run tests with coverage on PR branch
      run: |
        git checkout ${{ github.event.pull_request.head.sha }}
        npm ci
        npm run test:coverage
        cp coverage/coverage-summary.json coverage-pr.json

    - name: Generate coverage report
      id: coverage
      run: |
        # Extract coverage percentages
        if [ -f coverage-base.json ]; then
          BASE_COVERAGE=$(node -e "
            const coverage = require('./coverage-base.json');
            const total = coverage.total;
            if (total && total.lines && total.lines.pct !== undefined) {
              console.log(total.lines.pct);
            } else {
              console.log('0');
            }
          " 2>/dev/null || echo "0")
        else
          BASE_COVERAGE=0
        fi
        
        PR_COVERAGE=$(node -e "
          const coverage = require('./coverage-pr.json');
          const total = coverage.total;
          if (total && total.lines && total.lines.pct !== undefined) {
            console.log(total.lines.pct);
          } else {
            console.log('0');
          }
        " 2>/dev/null || echo "0")
        
        echo "Base coverage: $BASE_COVERAGE%"
        echo "PR coverage: $PR_COVERAGE%"
        echo "base_coverage=$BASE_COVERAGE" >> $GITHUB_OUTPUT
        echo "pr_coverage=$PR_COVERAGE" >> $GITHUB_OUTPUT
        
        # Check if coverage decreased
        if (( $(echo "$PR_COVERAGE < $BASE_COVERAGE" | bc -l) )); then
          echo "coverage_decreased=true" >> $GITHUB_OUTPUT
          echo "❌ Coverage decreased from $BASE_COVERAGE% to $PR_COVERAGE%"
        else
          echo "coverage_decreased=false" >> $GITHUB_OUTPUT
          echo "✅ Coverage maintained or improved: $BASE_COVERAGE% → $PR_COVERAGE%"
        fi

    - name: Comment PR
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      with:
        script: |
          const baseCoverage = '${{ steps.coverage.outputs.base_coverage }}';
          const prCoverage = '${{ steps.coverage.outputs.pr_coverage }}';
          const decreased = '${{ steps.coverage.outputs.coverage_decreased }}' === 'true';
          
          const emoji = decreased ? '❌' : '✅';
          const status = decreased ? 'decreased' : 'maintained/improved';
          const arrow = decreased ? '↓' : (baseCoverage === prCoverage ? '→' : '↑');
          
          const body = `## Test Coverage Report

          ${emoji} Coverage ${status}: ${baseCoverage}% ${arrow} ${prCoverage}%
          
          ${decreased ? '**This PR decreases test coverage. Please add tests to maintain or improve coverage.**' : 'Great job maintaining test coverage!'}`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: body
          });

    - name: Fail if coverage decreased
      if: steps.coverage.outputs.coverage_decreased == 'true'
      run: |
        echo "❌ Test coverage decreased. Please add tests to maintain or improve coverage."
        exit 1